### PR TITLE
Update expire time flag in get method

### PR DESCRIPTION
**Pull request by schafer14**

### CODE REVIEW

**Comment by ptarjan** [comment]
Didn't we already talk about this?

**Comment by schafer14** [comment]
Aren't these the changes you wanted? Sorry I'm a little confused.

**Comment by ptarjan** [comment]
`get` is not the place to do writes. The `put` method already supports your use-case.

**Comment by schafer14** [comment]
Really? I couldn't find it in the documentation or source. I might just fork then. Sorry to bother you.

**Comment by ptarjan** [comment]
https://github.com/ptarjan/node-cache/pull/66#issuecomment-227654504

**Comment by ptarjan** [comment]
Just call `put` in your client code.

**Comment by schafer14** [comment]
I'm not sure having to call `get` then `pull` any time I want look up a value is what I want to do. It makes the code a little bit harder to reason with.

I think it makes sense for me to just use a independent copy of the source.

**Comment by ptarjan** [comment]
...

**Pull request closed without merging**
