### PR TITLE
Updating the expire time on get based on flag

### PR DESCRIPTION
**Pull request by schafer14**
Added a flag to the get function to specify if the expiry time should be updated when a get is done.

### CODE REVIEW

**Comment by ptarjan** [comment]
Get is not the place for a write operation. Why can't you use `set` to update it?

**Comment by schafer14** [comment]
Yeah, that will work. I need to unbreak the tests too.

**Comment by ptarjan** [comment]
No, why can't you call `put(key, value, newtime)`?

**Comment by schafer14** [comment]
Yeah that's much simpler. Didn't think of that.

**Pull request closed without merging**
